#include $(srctree)/drivers/misc/mediatek/Makefile.custom
MTK_PLATFORM := $(subst ",,$(CONFIG_MTK_PLATFORM))
#ifeq ($(MTK_PLATFORM),mt6765)
obj-y += imx135mipiraw_Sensor_mt6765.o
#else
#obj-y += imx135mipiraw_Sensor.o
#endif


