#
# Makefile for all kinds of Fingerprint
#
obj-$(CONFIG_SUNWAVE_TEE_FINGERPRINT) += sunwave_fp_tee/
obj-$(CONFIG_GOODIX_FINGERPRINT) += goodix/
obj-$(CONFIG_FPC_FINGERPRINT) += fpc/
obj-$(CONFIG_MICROARRAY_FINGERPRINT) += microarray_fp/
obj-$(CONFIG_FPSENSOR_TEE) += fpsensor_tee/
