# include header files for MTK
#ccflags-y += -I$(srctree)/drivers/spi/mediatek/mt6797/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/ilitek_new/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include/

obj-y	+=  ilitek_fw.o
obj-y	+=  ilitek_i2c.o
obj-y	+=  ilitek_ic.o
obj-y	+=  ilitek_main.o
obj-y	+=  ilitek_plat_mtk.o
obj-y	+=  ilitek_mp.o
obj-y	+=  ilitek_node.o
obj-y	+=  ilitek_touch.o

